### ISSUE TITLE
There's a small contradiction in the README.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/triangle-classification#14]
Hello. The README says that the custom error class is supposed to be defined outside of the class definition of Triangle. However, the example that they provided shows the custom error being defined INSIDE of the Triangle class. I think the custom error should be defined inside of the Triangle class, or else Ruby will give a warning in the test output.

I know that this is a VERY minor issue, but thanks for checking this out.

Sdcrouse

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have corrected the readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
