### ISSUE TITLE
Instructions are unclear

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/triangle-classification#5]
`This custom error class can be defined inside the Triangle class, just like in the example from the previous exercise.`  (line 19, last sentence)

Which this should say is, should be defined in the same file as the Triangle class but outside of the Triangle class itself. 

I don't know which example it is talking about this lab must have been moved in the track.

@AnnJohn

**Comment by AnnJohn** [comment]
Assigned to @SophieDeBenedetto

**Comment by jmburges** [comment]
:+1:
