### ISSUE TITLE
Instructions on how to raise a custom error unclear to students

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/triangle-classification#6]
We haven't talked about raising errors at any point before this. Students don't know how to use it and are very confused. Just saw that @SophieDeBenedetto wrote a new code along `oo-inheritance-code-along` which explains inheritance but not raising errors. Maybe move the code along up in the track.

@AnnJohn

**Comment by AnnJohn** [comment]
@SophieDeBenedetto ^^

**Comment by SophieDeBenedetto** [comment]
@deniznida @AnnJohn 
this has been addressed in the web development with ruby on rails track. this lab has been improved and moved to a later unit where it follows a reading on raising errors. the web 09-15 class have been deploying from the wrong track.

**Comment by deniznida** [comment]
@SophieDeBenedetto we will switch to the right track now. thanks 

@AnnJohn we can close this issue then.

**Comment by AnnJohn** [comment]
Closing
